# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StartupViewApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SDWebImage', '~> 4.4.1'

  # Pods for StartupViewApp

  target 'StartupViewAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StartupViewAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
